name: whatsappweb
description: A Whatsapp webview(desktop) Android app for easy use when you have two phones and want to share whatsapp without need to login or sharing the whatsapp media files.

publish_to: 'none' 

version: 1.0.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/whatsapp.png"

flutter:
 
  uses-material-design: true

  assets:
    - images/whatsapp.png
